### ISSUE TITLE
Homepage title is wrong

### ISSUE THREAD

**Issue by nullfud** [sybrew/The-SEO-Framework-Extension-Manager#16]
The homepage title is wrong, when i search for nullfud, or authentic crypto news, it shows the following title in google:

nullFUD: Authentic Crypto News

Even though it's set to Authentic Crypto News - nullFUD (thats the name of the site once it's visited)

I am using premium, and the title fix is enabled. Please fix this.

**Comment by sybrew** [comment]
Hello!

Google may ignore your inputted SEO titles: https://support.google.com/webmasters/answer/35624#page-titles.

To decrease the chances of Google changing your titles, your titles should stay in the "green" pixel counter fields. Also, they should contain keywords related to the topic (which ought to be the expected search term). And lastly, do make sure the title is branded with the site name so that Google won't append the site name for you.

I hope this helps 😄 Cheers!
