### ISSUE TITLE
after updating to extension manger 2.0 focus is unavailable  

### ISSUE THREAD

**Issue by asianmusicguy** [sybrew/The-SEO-Framework-Extension-Manager#4]
Hi there since updating to extension manger focus is grayed out has it gone premium?

**Comment by asianmusicguy** [comment]
in fact all "Included extensions" seem grayed out and inactive

**Comment by sybrew** [comment]
Hi there!

I've explained why some extensions have moved to the new Essentials type in my comment here:
https://theseoframework.com/about/all-for-nothing/#comment-2504

You're safe to downgrade to 1.5.3 until the switch better suits you. But, I think you'll be happy to know there's a significant discount in the shop. It will allow you to use the latest, updated version freely on multiple sites.

I recommend reading the full blog post to get a better understanding of what's coming.

**Comment by sybrew** [comment]
I'm happy you appreciate all the work 😃 

I truly understand that not everyone welcomes this change, I wouldn't be happy as a user, either. So, I've added a discount in the shop to ease the transition that ends on December 31st, 2018.

If that doesn't work out for you, you might want to stick with the older version. Although I can't promise permanent compatibility, I do know that nothing needs to be done for a while that might compromise that &mdash; other than adding support for the Gutenberg editor.

TSFEM v1.5.3 will start to emit migration notifications in a few days. 
You can choose to ignore them, downgrade to v1.5.2, or add this little snippet to your website:
```php
function_exists( 'tsf_extension_manager' ) 
	and remove_action( 'admin_notices', [ tsf_extension_manager(), '_do_migration_notice' ] );
```

**Comment by asianmusicguy** [comment]
Ok well  point where discount is and I’ll go ahead and sign up if I can

**Comment by asianmusicguy** [comment]
I assume that it is the package marked essential for 29 a year?

**Comment by sybrew** [comment]
Yes, that's it 😄. It should stay that price for as long as the subscription is renewed.

**Comment by asianmusicguy** [comment]
Ok I have do so but i do not do such things often please assure me the
checkout is secure as possible and my data is safe i used paypal checkout
just in case

**Comment by sybrew** [comment]
I don't store any useful credit card information on my servers, as per PCI requirements. Even more so, the payment service providers don't save that information either, and PayPal chooses not to share any information at all. The providers perform fraud checks, authorize the transaction with your bank, and then maintain a revokable token. This way, no one can steal your payment information.

All logging data older than 30 days is automatically purged from the servers, too.

As for your privacy, please see the [privacy policy](https://theseoframework.com/privacy-policy/).

As for PayPal's security and protection, please see: 
https://www.paypal.com/ae/webapps/mpp/paypal-safety-and-security

Because PayPal's not clear on refunds for services, I've set up a clear and straightforward [refund policy](https://theseoframework.com/refund-policy/). This policy goes beyond the EU requirements of a 14-days window and applies to non-EU citizens too.

I hope this alleviates your concern 😃

**Comment by CathAnon** [comment]
I don't understand.  

I switched from Yoast and the comparable functionality that I was looking for from Yoast was in Articles and Focus.  These were in the plugin Extensions.  

I activated the plugin and tried to use Articles and Focus and it says the Extensions version will soon be unavailable 2019 and to download a newer version.  

I uploaded the new version and it looks like Articles and Focus are now no longer available.

What have I signed up for with your free plugin?  I have yet to gain any confidence before I would want to pay.  The biggest reason why I switched to you was because you seem to be able to handle the SEO and not bombard me with upgrade urgings.

Am I able to get Focus and Articles without paying?

Please advise.

**Comment by CathAnon** [comment]
ok ... I've just read your other posts and it explained the situation.

From the sounds of things, you deserve to be paid for your work which seems to be held in high regard by all who are commenting.

But I wish the change in your plugin's circumstances was indicated in the plugin before I got all my hopes up and downloaded it.  I do not have much funds and was looking for a free SEO alternative to Yoast.  I was thus excited about the potential of your Articles and Focus extensions.  I am disappointed I never got the chance to explore them.

Goodluck with your new business model.  From the sounds of it, you should have moved to a paid model some while back.

Cheers.

**Comment by sybrew** [comment]
Hi @CathAnon,

Thank you so much for understanding.

You can still get [the legacy version from WordPress.org](https://wordpress.org/plugins/the-seo-framework-extension-manager/), which includes those free extensions. So, you can yet explore them 😃.

I still deem the legacy version completely stable, and security support for it will continue until January 1st, 2019. The newer version has various bugfixes, supports PHP 7.3, is a little more polished, and will be supported indefinitely.

**Comment by sybrew** [comment]
Hi Cath,

In the changelogs of the extensions, you'll find what has changed since 2.0.0's launch (November 9th, 2018).

- [Articles' changelog](https://theseoframework.com/extensions/articles/#changelog)
- [Focus' changelog](https://theseoframework.com/extensions/focus/#changelog)

It's not much yet. Focus will get an overhaul for Gutenberg, and Articles will get an interface to select supported post types.

**Comment by sybrew** [comment]
I believe the dust has settled. If you still have questions regarding this subject, feel free to continue on this thread, regardless of it being closed.
