### ISSUE TITLE
Corrupted metadata when using the persistent object cache plugin

### ISSUE THREAD

**Issue by vralle** [sybrew/The-SEO-Framework-Extension-Manager#44]
**Describe the bug**
Serialization error with Docket Cache plugin (a persistent WordPress Object Cache plugin)

**To Reproduce**
1. Install and activate opcache zend extension
2. Install and activate Docket Cache plugin
3. See serialize/unserialize error log.
https://github.com/sybrew/The-SEO-Framework-Extension-Manager/blob/1adbf22ccdc99465e9d658ddfd4cca67228cb4ed/inc/traits/extension/post-meta.trait.php#L62

**Expected behavior**
The request can be retrieved from the cache as a PHP value.

**Additional context**
fix: replace unserialize -> maybe_unserialize

**Comment by sybrew** [comment]
Hi Vitaliy,

I like how you paid homage to the commit's title of https://github.com/sybrew/The-SEO-Framework-Extension-Manager/commit/11150f5790ba279359c90051dccfa48a30054e73 😄 

Anyway, this is not the first time I encountered an issue like this. https://wordpress.org/support/topic/can-destroy-serialized-data/

`maybe_unserialize()` mitigates double-unserialization issues; [but introduces them too[(https://wpdeeply.com/wordpress-and-multiple-maybe_unserialize/) when not tightly controlled. This should not be an issue in our case since we use a Key-Value store; yet, using `maybe_unserialize()` would fix a symptom of an underlying problem.

I'm not sure what Docket Cache does to fault the metadata -- I believe they might try to unserialize the data and not return it as is intended, but I haven't read the code. I suggest reaching out to them about this issue. My inbox is open for communication.

**Comment by vralle** [comment]
Hi Sybre! By this time I don't have any projects using WP)

But I do remember that ever since my projects started using strict types and PHPStan, the only way to process data from a WP without errors was to use the input type as "mixed". For example, WP hooks do not have data type checking, which can lead to unexpected results. Type checking increases code size, but this is common practice when writing code in 2024)
