### ISSUE TITLE
Transport Extension Missing

### ISSUE THREAD

**Issue by gittershubbers** [sybrew/The-SEO-Framework-Extension-Manager#61]
The "Transport" extension is missing from the list of extensions in the "Extension Manager" plugin. Not activate button greyed out, but not listed at all. Your website states this extension is Free and included in the "Extension Manage" bundle.
https://theseoframework.com/extensions/transport/

**Comment by sybrew** [comment]
Hello!

The website reflects the latest plugin version, which isn't always released to the public yet.
This latest version introduces the Transport extension. The discussion for that extension is at https://github.com/sybrew/the-seo-framework/issues/548.

I'm amidst releasing this latest version, but I found some issues that still need fixing before launch. ETA within two days, otherwise next week from Tuesday.

**Comment by sybrew** [comment]
I'm happy to announce that Transport is now available! It supports migrating from Yoast SEO and Rank Math, with All in One SEO and SEOPress coming soon.

Cheers!
