### ISSUE TITLE
Bug: error 2001 and 6001

### ISSUE THREAD

**Issue by bonakor** [sybrew/The-SEO-Framework-Extension-Manager#74]
Hi,
I have a multisite network. The Extension manager is enabled at network level, but the issue happens also when I activate the extension on  per site basis.

I have errors 2001 and 6001. It's unfortunate because it makes my news sitemap unreachable.

How can I avoid this, please?

**Comment by sybrew** [comment]
Hello!

Sorry for the trouble! If you cannot reconnect the sites, please [get in touch with me here](https://theseoframework.com/contact/).

In Extension Manager 2.6.1, I changed the option verification algorithm, so this issue should become less likely to occur.

If you are using an earlier version, or the sites experiencing this issue have used an earlier version of Extension Manager in the past, you may have a plugin activated that rotates the security hashes on `wp-config.php`.

Those keys only need changing when you suspect they've leaked out. Even then, it's difficult to use those nefariously. You can safely leave them static by disabling the related "security" option. One plugin I know of that does this is iThemes Security.

If this issue occurs at least twice (on one site) after upgrading to Extension Manager v2.6.1, the paths leading to your WordPress installation of the server may be changing sporadically. This could happen on a complex node network where symbolic links aren't registered or read consistently -- an issue I have been unable to reproduce.

**Comment by bonakor** [comment]
Hello Sybrew,
thank you for your quick answer.

I think that must be it: I deploy using "atomic deploys", and I symlink new releases to the current on each deploy.

I might be doing it wrong. Would you have an advice on how to "symlink" the good way?

**Comment by sybrew** [comment]
Hello again!

The main plugin file should maintain the same path as it had during account activation.

More users have been finding issues with our new verification system (it mitigates bypassing our licensing), which wouldn't have been necessary if the AUTH keys never changed. Still, user retention increased by 10% after I changed this in v2.6.1, and perhaps I should make the verification system even more lenient so you can keep doing what you are without problems.

**Comment by bonakor** [comment]
I could very well symlink to the plugin and have it in a specific folder to avoid it moving on each release. But it makes maintenance a bit more complicated on my side. Would it work?

I very rarely change my AUTH KEYS (I didn't change it for a long time on this network). So if you can improve things on your side, I take it.

And if the issues persists, I'll check for other ways to have news sitemap because I need a stable solution.

**Comment by sybrew** [comment]
You can test it quite easily: activate the account, perform the deploy, and see if you get the error.

The AUTH keys is something I removed support for because too many users kept changing those without knowing what they actually do.

I'll test this later today and see if I can recreate the error consistently, and deploy a patch if possible. ([note to self](https://developer.wordpress.org/reference/functions/wp_register_plugin_realpath/))

**Comment by bonakor** [comment]
Yes, I just tested and when I deploy, I get the error.

I'll try later today to symlink to the Extension folder and see if it fixes it

**Comment by sybrew** [comment]
Hi @bonakor,

Are you able to edit PHP files, and do those edited PHP files stay the same between deployments?

If so, go to `wp-content/plugins/the-seo-framework-extension-manager/inc/classes/core.class.php`, and change line 948 from:
```php
				'salt' => 's' . md5( \dirname( TSF_EXTENSION_MANAGER_PLUGIN_BASE_FILE ) )
```
to:
```php
				'salt' => 's' . md5( \dirname( realpath( TSF_EXTENSION_MANAGER_PLUGIN_BASE_FILE ) ) )
```

Extension Manager should immediately send the 2001 and 6001 errors. But, after reconnection, those errors should no longer appear on redeployment -- provided, of course, that the updated code with `realpath()` is still there after redeploying.

Could you please verify this for me? Thank you!

If this works, that new verification system should work with any site with or without symbolic links.

**Comment by bonakor** [comment]
Hi @sybrew 
Yes, when I edit PHP files, the files stay the same but their path changes because I have one folder per release.

I edited the core.class.php, and deployed. I activated my account. Then I made another deploy (the php code is still the fixed one). And my acount was logged out again.

Could it be because I have a folder per release?

For some premium plugins I use like the Oflload media or even WP Rocket, I have been able to put my credentials in my .env. Is that something feasible?

**Comment by bonakor** [comment]
Ah, and now the errors I get are 2001 and 6002

**Comment by sybrew** [comment]
The code changes will not work around this issue if the folder changes every release.

If you update the symlink of the wp-content folder during deployment so that the path will always stay the same, then the changed code should work.

Unlike WP Rocket et al., Extension Manager protects against sharing credentials from one site to another. This is why there's no public nullification of our plugins. So, even if you provide those credentials via the environment (there are constants for Extension Manager), that would not workaround this issue.

How you handle WordPress is not standard and something I had not foreseen. I shall look into another method for verification or at least provide you with a toggle. I'm also amidst upgrading our entire API for extremely high performance so we can offload the license verification from our user's site to ours.

Here is something that will work for you instantly, without having to mess with symbolic links:

1. Deactivate the account on your website.
2. Remove line `209` at `wp-content/plugins/the-seo-framework-extension-manager/inc/classes/accountactivation.class.php`.
   - That line says `			'_instance_version' => '2.0', // If not in database, assume 1.0`
   - You do not need to revert the other code change.
3. You can now reconnect your account.
4. You can safely update the plugin. As long as you do not disconnect your account, it will keep using the old instance version. And as long as you do not change the AUTH keys, the verification will stay intact.

I shall provide a constant that forces the verification instance at '1.0' between updates. I'll post it here when I have it ready.

**Comment by bonakor** [comment]
Hy @sybrew 
Thank you. I'll do that and come back to you if it doesn't work.

**Comment by bonakor** [comment]
Hello @sybrew,
I'm sorry, and maybe I did something wrong:
I deployed a new version of my code.
The Extension Manager told me the local instance if out of sync. So I disconneded and reconnected it.

So I'm unsure if your solution worked.

**Comment by sybrew** [comment]
Hi @bonakor,

I noticed you deleted your follow-up reply. Does everything work as intended now?

**Comment by bonakor** [comment]
Hi,
Yeah, at first it didn't but redeploying fixed it. So yeah now it's working as intended. Thank you. I'll update my other sites with the same issue

**Comment by sybrew** [comment]
Hi @bonakor, sorry for the delay.

In the next update, `TSF_EXTENSION_MANAGER_INSTANCE_VERSION` will be available. It accepts any of three values as a string:

- `'1.0'` - This is the old AUTH-key-based verification system. This is the most reliable, but iThemes Security thought better.
- `'2.0'` - This is the current path-based verification system. This is what you're finding issues with.
- `'3.0'` - This is the upcoming site-url-based verification system (available from the next version). This is the most logical for users and may even work best for you.

Only after completely disconnecting the account via Extension Manager's dashboard will you be able to switch versions using the constant. This version is then stored for future use until disconnected again.

Some takeaways:
- '1.0' will fail when the AUTH key and salt pair in `wp-config.php` change.
- '2.0' will fail if the location of the plugin folder changes relative to the root folder of the operating system.
- '3.0' will fail when the site URL changes.

**Comment by bonakor** [comment]
Hello @sybrew,
Thank you for that. Seems nice.

Do you have an ETA on the next update?

**Comment by sybrew** [comment]
Hopefully, next week. Google's banging on my door about GA4.

**Comment by bonakor** [comment]
Don't tell me about it. But thankfully some clients agree to switch to another provider.

I'll be on holidays from Thursday to June 24. I'll switch when I'm back then.

**Comment by sybrew** [comment]
I hope you're enjoying your holidays! When you get back, Extension Manager v2.6.2 will be waiting for you 😃

**Comment by bonakor** [comment]
Hi Sybrew,

Holidays were good but a bit short, thanks!

I just uploaded. Should I define the constant or does it default to version 3.0?

**Comment by sybrew** [comment]
From Extension Manager v2.6.2, the instance version will default to `'3.0'` for sites that have been entirely disconnected (so you can see the "get your key" welcome screen). Not-disconnected sites will still use older versions.

**Comment by bonakor** [comment]
Alright, perfect.

Thanks!
